name: Docker CI

on:
  push:
  pull_request:

jobs:
  lint-dockerfile:
    name: Lint Dockerfile with Hadolint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: app/Dockerfile
          failure-threshold: warning
